[package]
name = "queuing-system-modeling"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "simulator"
]


[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.160", features = ["derive"] }
